'use client';

import { useEffect, useMemo, useState } from 'react';
import { Building2, Download, Pencil, Plus, Trash2, TrendingUp } from 'lucide-react';
import { toast } from 'sonner';
import { companyService, ICompanyEmployee, ICompanySale } from '@/services/companyService';

const input = 'rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs text-white outline-none focus:border-indigo-500';
const downloadCsv = (rows: string[][]) => { const text = rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' })); link.download = 'filtered-sales.csv'; link.click(); URL.revokeObjectURL(link.href); };

type Filters = { employee: string; month: string; from: string; to: string };
const emptyFilters: Filters = { employee: '', month: '', from: '', to: '' };

export function AdminSalesSection() {
  const [sales, setSales] = useState<ICompanySale[]>([]); const [employees, setEmployees] = useState<ICompanyEmployee[]>([]); const [filters, setFilters] = useState<Filters>(emptyFilters); const [editing, setEditing] = useState<ICompanySale | null>(null); const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({ name: '', country: '', system: '', connectedBy: '', amount: 0, paymentMethod: 'Other' as ICompanySale['paymentMethod'], saleDate: new Date().toISOString().slice(0, 10) });
  useEffect(() => { companyService.getSales().then(setSales).catch(() => toast.error('Unable to load sales')); companyService.getEmployees().then(setEmployees).catch(() => toast.error('Unable to load employees')); }, []);
  const filtered = useMemo(() => sales.filter((sale) => { const date = sale.saleDate; return (!filters.employee || sale.connectedBy === filters.employee) && (!filters.month || date.startsWith(filters.month)) && (!filters.from || date >= filters.from) && (!filters.to || date <= filters.to); }), [sales, filters]);
  const openAdd = () => { setEditing(null); setForm({ name: '', country: '', system: '', connectedBy: '', amount: 0, paymentMethod: 'Other', saleDate: new Date().toISOString().slice(0, 10) }); setAdding(true); };
  const openEdit = (sale: ICompanySale) => { setEditing(sale); setForm({ name: sale.name, country: sale.country, system: sale.system, connectedBy: sale.connectedBy, amount: sale.amount, paymentMethod: sale.paymentMethod, saleDate: sale.saleDate }); setAdding(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { const result = editing ? await companyService.updateSale(editing._id, form) : await companyService.createSale(form); setSales((current) => editing ? current.map((sale) => sale._id === editing._id ? result : sale) : [result, ...current]); setAdding(false); setEditing(null); toast.success(editing ? 'Sale updated' : 'Sale created'); } catch (error: any) { toast.error(error.response?.data?.message || 'Unable to save sale'); } };
  const remove = async (id: string) => { if (!window.confirm('Delete this sale?')) return; try { await companyService.deleteSale(id); setSales((current) => current.filter((sale) => sale._id !== id)); toast.success('Sale deleted'); } catch { toast.error('Unable to delete sale'); } };
  const revenue = filtered.reduce((total, sale) => total + sale.amount, 0);
  return <section className="min-h-full space-y-5 overflow-y-auto bg-slate-950 p-6 text-slate-100"><header className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-white"><TrendingUp className="h-6 w-6 text-emerald-400" /> Sales Revenue</h1><p className="text-sm text-slate-400">Manage company sales transactions.</p></div><button onClick={openAdd} className="flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white"><Plus className="h-4 w-4" />Add Sale</button></header>
    <div className="flex flex-wrap items-end gap-2 rounded-xl border border-slate-800 bg-slate-900/70 p-3"><label className="text-[11px] text-slate-400">Closed by<select value={filters.employee} onChange={(event) => setFilters({ ...filters, employee: event.target.value })} className={`${input} ml-1`}><option value="">Everyone</option>{employees.map((employee) => <option key={employee._id} value={employee.name}>{employee.name} · {employee.role}</option>)}</select></label><label className="text-[11px] text-slate-400">Month & year<input type="month" value={filters.month} onChange={(event) => setFilters({ ...filters, month: event.target.value, from: '', to: '' })} className={`${input} ml-1`} /></label><label className="text-[11px] text-slate-400">Start date<input type="date" value={filters.from} onChange={(event) => setFilters({ ...filters, from: event.target.value, month: '' })} className={`${input} ml-1`} /></label><label className="text-[11px] text-slate-400">End date<input type="date" value={filters.to} onChange={(event) => setFilters({ ...filters, to: event.target.value, month: '' })} className={`${input} ml-1`} /></label><button onClick={() => setFilters(emptyFilters)} className="rounded-lg bg-slate-700 px-3 py-2 text-xs text-white">Clear</button><button onClick={() => downloadCsv([['Customer', 'Country', 'System', 'Closed By', 'Payment', 'Date', 'Amount'], ...filtered.map((sale) => [sale.name, sale.country, sale.system, sale.connectedBy, sale.paymentMethod, sale.saleDate, String(sale.amount)])])} className="ml-auto flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><Download className="h-3.5 w-3.5" />Export CSV</button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Filtered revenue" value={`$${revenue.toLocaleString()}`} /><Metric label="Closed deals" value={filtered.length} /><Metric label="Average deal" value={`$${filtered.length ? Math.round(revenue / filtered.length).toLocaleString() : 0}`} /></div>
    {adding && <form onSubmit={save} className="grid gap-3 rounded-xl border border-indigo-500/30 bg-slate-900 p-4 md:grid-cols-4">{([['name', 'Customer'], ['country', 'Country'], ['system', 'System'], ['connectedBy', 'Closed by']] as const).map(([key, label]) => <label key={key} className="space-y-1 text-xs text-slate-400">{label}<input required value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className={`${input} block w-full`} /></label>)}<label className="space-y-1 text-xs text-slate-400">Amount<input type="number" min="0" value={form.amount} onChange={(event) => setForm({ ...form, amount: Number(event.target.value) })} className={`${input} block w-full`} /></label><label className="space-y-1 text-xs text-slate-400">Sale date<input type="date" value={form.saleDate} onChange={(event) => setForm({ ...form, saleDate: event.target.value })} className={`${input} block w-full`} /></label><div className="flex items-end gap-2"><button className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white">Save</button><button type="button" onClick={() => setAdding(false)} className="rounded-lg bg-slate-700 px-3 py-2 text-xs text-white">Cancel</button></div></form>}
    <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-xs text-slate-300"><thead className="bg-slate-900 text-slate-400"><tr>{['Customer', 'System', 'Closed By', 'Payment', 'Date', 'Amount', 'Actions'].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{filtered.map((sale) => <tr key={sale._id}><td className="p-3 font-semibold text-white">{sale.name}<span className="block text-slate-500">{sale.country}</span></td><td className="p-3"><Building2 className="mr-1 inline h-3.5 w-3.5" />{sale.system}</td><td className="p-3">{sale.connectedBy}</td><td className="p-3">{sale.paymentMethod}</td><td className="p-3">{sale.saleDate}</td><td className="p-3 text-emerald-400">${sale.amount.toLocaleString()}</td><td className="p-3"><button onClick={() => openEdit(sale)} className="mr-2 text-indigo-400" title="Edit sale"><Pencil className="inline h-4 w-4" /></button><button onClick={() => void remove(sale._id)} className="text-rose-400" title="Delete sale"><Trash2 className="inline h-4 w-4" /></button></td></tr>)}</tbody></table></div>
  </section>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-white">{value}</p></div>; }
