'use client';

import { useEffect, useMemo, useState } from 'react';
import { Download, Filter, TrendingUp, UserPlus } from 'lucide-react';
import { toast } from 'sonner';
import { companyService, ICompanyEmployee, ICompanyLead, ICompanySale } from '@/services/companyService';
import { matchesBusinessDateFilters } from '@/lib/businessDate';

const input = 'rounded-lg border border-slate-700 bg-slate-950 px-2.5 py-2 text-xs text-white outline-none focus:border-indigo-500';
const csv = (name: string, rows: string[][]) => { const text = rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' })); link.download = name; link.click(); URL.revokeObjectURL(link.href); };

type Filters = { employee: string; month: string; from: string; to: string };
const matchesDate = (value: string | undefined, filters: Filters) => matchesBusinessDateFilters(value, filters);

function FilterBar({ filters, setFilters, employees, label }: { filters: Filters; setFilters: (value: Filters) => void; employees: ICompanyEmployee[]; label: string }) {
  return <div className="flex flex-wrap items-end gap-2 rounded-xl border border-slate-800 bg-slate-900/70 p-3"><Filter className="mb-2 h-4 w-4 text-indigo-400" /><label className="text-[11px] text-slate-400">{label}<select value={filters.employee} onChange={(event) => setFilters({ ...filters, employee: event.target.value })} className={`${input} ml-1`}><option value="">Everyone</option>{employees.map((employee) => <option key={employee._id} value={employee.name}>{employee.name} · {employee.role}</option>)}</select></label><label className="text-[11px] text-slate-400">Month<input type="month" value={filters.month} onChange={(event) => setFilters({ ...filters, month: event.target.value, from: '', to: '' })} className={`${input} ml-1`} /></label><label className="text-[11px] text-slate-400">Start date<input type="date" value={filters.from} onChange={(event) => setFilters({ ...filters, from: event.target.value, month: '' })} className={`${input} ml-1`} /></label><label className="text-[11px] text-slate-400">End date<input type="date" value={filters.to} onChange={(event) => setFilters({ ...filters, to: event.target.value, month: '' })} className={`${input} ml-1`} /></label><button onClick={() => setFilters({ employee: '', month: '', from: '', to: '' })} className="rounded-lg bg-slate-700 px-3 py-2 text-xs text-white">Clear</button></div>;
}

export function FilteredLeadsSection() {
  const [leads, setLeads] = useState<ICompanyLead[]>([]); const [employees, setEmployees] = useState<ICompanyEmployee[]>([]); const [filters, setFilters] = useState<Filters>({ employee: '', month: '', from: '', to: '' });
  useEffect(() => { companyService.getLeads().then(setLeads).catch(() => toast.error('Unable to load leads')); companyService.getEmployees().then(setEmployees).catch(() => toast.error('Unable to load employees')); }, []);
  const filtered = useMemo(() => leads.filter((lead) => (!filters.employee || lead.connectedBy === filters.employee) && matchesDate((lead as ICompanyLead & { createdAt?: string }).createdAt, filters)), [leads, filters]);
  const exportRows = () => csv('filtered-leads.csv', [['Lead', 'Country', 'System', 'Contact', 'Connected By', 'Connected', 'Sale'], ...filtered.map((lead) => [lead.name, lead.country, lead.system, lead.contactNo, lead.connectedBy, lead.connected, lead.isSale])]);
  return <section className="min-h-full space-y-5 overflow-y-auto bg-slate-950 p-6 text-slate-100"><header className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-white"><UserPlus className="h-6 w-6 text-sky-400" /> Leads</h1><p className="text-sm text-slate-400">Filtered leads connected by each employee.</p></div><button onClick={exportRows} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><Download className="h-4 w-4" />Export filtered CSV</button></header><FilterBar filters={filters} setFilters={setFilters} employees={employees} label="Connected by" /><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-xs text-slate-300"><thead className="bg-slate-900 text-slate-400"><tr>{['Lead', 'Country', 'System', 'Contact', 'Connected By', 'Connected', 'Sale'].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{filtered.map((lead) => <tr key={lead._id}><td className="p-3 font-semibold text-white">{lead.name}</td><td className="p-3">{lead.country}</td><td className="p-3">{lead.system}</td><td className="p-3">{lead.contactNo}</td><td className="p-3">{lead.connectedBy}</td><td className="p-3">{lead.connected}</td><td className="p-3">{lead.isSale}</td></tr>)}</tbody></table></div></section>;
}

export function FilteredSalesSection() {
  const [sales, setSales] = useState<ICompanySale[]>([]); const [employees, setEmployees] = useState<ICompanyEmployee[]>([]); const [filters, setFilters] = useState<Filters>({ employee: '', month: '', from: '', to: '' });
  useEffect(() => { companyService.getSales().then(setSales).catch(() => toast.error('Unable to load sales')); companyService.getEmployees().then(setEmployees).catch(() => toast.error('Unable to load employees')); }, []);
  const filtered = useMemo(() => sales.filter((sale) => (!filters.employee || sale.connectedBy === filters.employee) && matchesDate(sale.saleDate, filters)), [sales, filters]);
  const revenue = filtered.reduce((total, sale) => total + sale.amount, 0); const exportRows = () => csv('filtered-sales.csv', [['Customer', 'Country', 'System', 'Closed By', 'Payment', 'Date', 'Amount'], ...filtered.map((sale) => [sale.name, sale.country, sale.system, sale.connectedBy, sale.paymentMethod, sale.saleDate, String(sale.amount)])]);
  return <section className="min-h-full space-y-5 overflow-y-auto bg-slate-950 p-6 text-slate-100"><header className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-white"><TrendingUp className="h-6 w-6 text-emerald-400" /> Sales</h1><p className="text-sm text-slate-400">Filtered sales closed by each employee.</p></div><button onClick={exportRows} className="flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white"><Download className="h-4 w-4" />Export filtered CSV</button></header><FilterBar filters={filters} setFilters={setFilters} employees={employees} label="Closed by" /><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">Filtered revenue</p><p className="mt-1 text-2xl font-bold text-emerald-400">${revenue.toLocaleString()}</p></div><div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">Closed deals</p><p className="mt-1 text-2xl font-bold text-white">{filtered.length}</p></div></div><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-xs text-slate-300"><thead className="bg-slate-900 text-slate-400"><tr>{['Customer', 'System', 'Closed By', 'Payment', 'Date', 'Amount'].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{filtered.map((sale) => <tr key={sale._id}><td className="p-3 font-semibold text-white">{sale.name}</td><td className="p-3">{sale.system}</td><td className="p-3">{sale.connectedBy}</td><td className="p-3">{sale.paymentMethod}</td><td className="p-3">{sale.saleDate}</td><td className="p-3 text-emerald-400">${sale.amount.toLocaleString()}</td></tr>)}</tbody></table></div></section>;
}
