'use client';

import { Hash, MoreVertical, Pencil, Plus, Trash2, Users } from 'lucide-react';
import type { IGroupChannel } from '../types';

type GroupsSectionProps = { groups: IGroupChannel[]; onCreateGroup: () => void; onEditGroup: (group: IGroupChannel) => void; onDeleteGroup: (group: IGroupChannel) => void };

export function GroupsSection({ groups, onCreateGroup, onEditGroup, onDeleteGroup }: GroupsSectionProps) {
  return <div className="space-y-5 overflow-y-auto p-6"><header className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h1 className="text-2xl font-bold text-white">Channels & Workspace Groups</h1><p className="text-sm text-slate-400">Manage public channels and private employee groups.</p></div><button onClick={onCreateGroup} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-semibold text-white transition hover:bg-indigo-500"><Plus className="h-4 w-4" /> Create New Channel</button></header>{groups.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-800 p-10 text-center text-sm text-slate-500">No groups have been created yet.</div> : <div className="grid gap-4 md:grid-cols-2">{groups.map((group) => <div key={group.id} className="flex flex-col justify-between space-y-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 hover:border-slate-700"><div><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2.5"><div className="rounded-xl bg-indigo-600/20 p-2 text-indigo-400"><Hash className="h-5 w-5" /></div><h3 className="text-base font-bold text-white">{group.name}</h3></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider ${group.privacy === 'private' ? 'bg-amber-500/10 text-amber-400' : 'bg-emerald-500/10 text-emerald-400'}`}>{group.privacy}</span><div className="relative group"><button aria-label={`Actions for ${group.name}`} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-800 hover:text-white"><MoreVertical className="h-4 w-4" /></button><div className="absolute right-0 top-8 z-10 hidden w-32 overflow-hidden rounded-lg border border-slate-700 bg-slate-900 py-1 shadow-xl group-focus-within:block group-hover:block"><button onClick={() => onEditGroup(group)} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs text-slate-200 hover:bg-slate-800"><Pencil className="h-3.5 w-3.5" /> Edit</button><button onClick={() => onDeleteGroup(group)} className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs text-rose-300 hover:bg-slate-800"><Trash2 className="h-3.5 w-3.5" /> Delete</button></div></div></div></div><p className="mt-3 text-xs leading-relaxed text-slate-400">{group.description || 'No description'}</p></div><div className="flex items-center justify-between border-t border-slate-800/80 pt-3 text-xs text-slate-400"><span className="flex items-center gap-1.5"><Users className="h-4 w-4 text-slate-500" />{group.membersCount} Members</span><span className="text-[10px] text-slate-500">Created: {group.createdDate}</span></div></div>)}</div>}</div>;
}
