'use client';

import { CheckCircle2, DollarSign, MessageSquare, Target, TrendingUp, UserPlus, Users } from 'lucide-react';
import type { Dispatch, SetStateAction } from 'react';
import type { IEmployee, NavSection } from '../types';

type OverviewSectionProps = { employees: IEmployee[]; setActiveSection: Dispatch<SetStateAction<NavSection>>; onAddEmployee: () => void; employee?: { name: string; monthlySalesTarget: number; monthlySalesAchieved: number; leadsAssigned: number; leadsConverted: number; role: string }; companyName?: string; isEmployee?: boolean };

export function OverviewSection({ employees, setActiveSection, onAddEmployee, employee, companyName, isEmployee = false }: OverviewSectionProps) {
  const target = employee?.monthlySalesTarget || 0;
  const achieved = employee?.monthlySalesAchieved || 0;
  const progress = target ? Math.min(100, Math.round((achieved / target) * 100)) : 0;
  return (
    <div className="p-6 overflow-y-auto space-y-6">
      <header className="flex flex-wrap justify-between items-center gap-4 pb-4 border-b border-slate-800"><div><h1 className="text-2xl font-bold text-white">Hello {isEmployee ? employee?.name || 'there' : 'Admin'}</h1><p className="text-sm text-slate-400">{isEmployee ? 'Your performance, targets, and workspace activity.' : 'Real-time metrics, employee sales performance, and workspace activity.'}</p></div><div className="flex gap-2">{!isEmployee && <button onClick={onAddEmployee} className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold rounded-xl flex items-center gap-2 transition"><UserPlus className="h-4 w-4" /> Add Employee</button>}<button onClick={() => setActiveSection('chat')} className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-xl flex items-center gap-2 transition shadow-md shadow-indigo-600/30"><MessageSquare className="h-4 w-4" /> Launch Chat Workspace</button></div></header>
      <div className="grid gap-5 md:grid-cols-4"><div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/60"><div className="flex items-center justify-between text-slate-400 mb-2"><span className="text-xs uppercase font-semibold">{isEmployee ? 'Achieved' : 'Total Revenue Achieved'}</span><DollarSign className="h-5 w-5 text-emerald-400" /></div><p className="text-3xl font-bold text-white">{isEmployee ? `$${achieved.toLocaleString()}` : '$182,200'}</p><p className="text-[11px] text-emerald-400 mt-2 flex items-center gap-1"><TrendingUp className="h-3 w-3" />{isEmployee ? 'Current target performance' : ' +18.4% monthly target'}</p></div><div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/60"><div className="flex items-center justify-between text-slate-400 mb-2"><span className="text-xs uppercase font-semibold">{isEmployee ? 'Leads Assigned' : 'Total Workforce'}</span><Users className="h-5 w-5 text-indigo-400" /></div><p className="text-3xl font-bold text-white">{isEmployee ? employee?.leadsAssigned || 0 : employees.length}</p><p className="text-[11px] text-slate-400 mt-2">{isEmployee ? 'Assigned to you' : 'Active sales performers'}</p></div><div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/60"><div className="flex items-center justify-between text-slate-400 mb-2"><span className="text-xs uppercase font-semibold">Target Completion</span><Target className="h-5 w-5 text-amber-400" /></div><p className="text-3xl font-bold text-white">{isEmployee ? `${progress}%` : '86.7%'}</p><p className="text-[11px] text-slate-400 mt-2">{isEmployee ? `$${target.toLocaleString()} assigned target` : '$210,000 Total Monthly Goal'}</p></div><div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/60"><div className="flex items-center justify-between text-slate-400 mb-2"><span className="text-xs uppercase font-semibold">{isEmployee ? 'Leads Converted' : 'System Health'}</span><CheckCircle2 className="h-5 w-5 text-emerald-400" /></div><p className="text-xl font-bold text-emerald-400 mt-1">{isEmployee ? employee?.leadsConverted || 0 : 'Optimal (99.9%)'}</p><p className="text-[11px] text-slate-400 mt-2">{isEmployee ? 'Your completed conversions' : 'All microservices active'}</p></div></div>
      <div className="grid gap-6 lg:grid-cols-3"><div className="lg:col-span-2 p-5 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4"><h3 className="text-sm font-bold uppercase tracking-wider text-slate-300">Top Performing Sales Leaders</h3><div className="space-y-3">{employees.slice(0, 3).map((emp) => { const percent = Math.round((emp.salesTarget.monthlyAchieved / emp.salesTarget.monthlyTarget) * 100); return <div key={emp.id} className="flex items-center justify-between p-3.5 rounded-xl bg-slate-950/60 border border-slate-800/60 text-xs"><div className="flex items-center gap-3"><div className={`h-8 w-8 rounded-full bg-gradient-to-tr ${emp.avatarBg} flex items-center justify-center text-white font-bold`}>{emp.name.split(' ').map(n => n[0]).join('')}</div><div><p className="font-bold text-slate-100">{emp.name}</p><p className="text-[10px] text-slate-400">{emp.role}</p></div></div><div className="text-right"><p className="font-bold text-emerald-400">${emp.salesTarget.monthlyAchieved.toLocaleString()} / ${emp.salesTarget.monthlyTarget.toLocaleString()}</p><span className="text-[10px] text-slate-400">{percent}% Goal Achieved</span></div></div>; })}</div></div><div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4"><h3 className="text-sm font-bold uppercase tracking-wider text-slate-300">Tenant Info</h3><div className="space-y-2.5 text-xs text-slate-300"><div className="flex justify-between border-b border-slate-800 pb-2"><span className="text-slate-400">Organization:</span><strong className="text-white">Techno Sky Solutions</strong></div><div className="flex justify-between border-b border-slate-800 pb-2"><span className="text-slate-400">Plan:</span><span className="text-indigo-400 font-bold">Enterprise Tier</span></div><div className="flex justify-between border-b border-slate-800 pb-2"><span className="text-slate-400">Primary Domain:</span><span className="font-mono text-slate-200">technosky.io</span></div><div className="flex justify-between border-b border-slate-800 pb-2"><span className="text-slate-400">Active Licenses:</span><span className="font-bold text-white">42 / 100</span></div></div></div></div>
    </div>
  );
}
