'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, DollarSign } from 'lucide-react';
import { toast } from 'sonner';
import { companyService, ICompanyEmployee, ILeaveRecord } from '@/services/companyService';
import { getBusinessMonthString } from '@/lib/businessDate';

export function SalaryLeaveSection() {
  const [employees, setEmployees] = useState<ICompanyEmployee[]>([]); const [leaves, setLeaves] = useState<ILeaveRecord[]>([]); const [month, setMonth] = useState(getBusinessMonthString());
  useEffect(() => { companyService.getEmployees().then(setEmployees).catch(() => toast.error('Unable to load employees')); companyService.getLeave(month).then(setLeaves).catch(() => toast.error('Unable to load leave')); }, [month]);
  const visible = useMemo(() => employees.filter((employee) => !employee.salaryMonth || employee.salaryMonth === month), [employees, month]);
  const update = async (employee: ICompanyEmployee, credited: boolean) => { try { const result = await companyService.updateEmployee(employee._id, { salaryAmount: employee.salaryAmount || 0, salaryMonth: month, salaryCredited: credited }); setEmployees((current) => current.map((item) => item._id === employee._id ? { ...item, ...result } : item)); } catch { toast.error('Unable to update salary'); } };
  return <section className="min-h-full space-y-5 overflow-y-auto bg-slate-950 p-6 text-slate-100"><header className="flex items-center justify-between border-b border-slate-800 pb-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-white"><DollarSign className="h-6 w-6 text-emerald-400" /> Salary & Leave</h1><p className="text-sm text-slate-400">Manage employee salary credit status and monthly records.</p></div><label className="text-xs text-slate-400">Month<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label></header><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-xs text-slate-300"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3">Employee</th><th className="p-3">Role</th><th className="p-3">Salary</th><th className="p-3">Month</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody className="divide-y divide-slate-800">{visible.map((employee) => <tr key={employee._id}><td className="p-3 font-semibold text-white">{employee.name}</td><td className="p-3">{employee.role}</td><td className="p-3">${(employee.salaryAmount || 0).toLocaleString()}</td><td className="p-3">{month}</td><td className="p-3">{employee.salaryCredited ? 'CREDITED' : 'NOT CREDITED'}</td><td className="p-3"><button onClick={() => void update(employee, !employee.salaryCredited)} className="flex items-center gap-1 rounded-lg bg-indigo-600 px-2 py-1.5 text-xs text-white"><Check className="h-3.5 w-3.5" />Mark {employee.salaryCredited ? 'not credited' : 'credited'}</button></td></tr>)}</tbody></table></div><div className="flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-4 w-4" />{visible.length} employee records for {month}</div></section>;
}
